---
title: "Meeting Minutes 4"
description: ""
author: "David Chiam, Enrico Sebastian, Liu Chih Yuan"
date: "22 May 2025"
date-modified: "14 June 2025"
format: html
editor: visual
execute: 
  eval: true
  echo: true
  warning: false
  freeze: true
---

**Date Conducted:** 14 June 2025

**Meeting time:** 1600hrs - 1800 hrs

**Location:** Singapore Management University

**Agenda on this meeting:**

1.  To start working on the SHINY project
2.  To discuss the answers generated by team members for the questions
3.  To analyse and discuss on the possible data that will be used for this project based on the answers provided by each of the team members for the questions

**What has been discussed during this meeting?**

1.  In this meeting we will be gathering our answers for all of the questions as these answers will now be collated to be put inside our SHINY app

2.  We will also be starting works on our SHINY app and coding works are expected to begin by today

3.  Based on our proposal, we also discussed on how our finalised SHINY app will look like; be it the dashboard, menu pages, etc

**Preparing for next Meeting:**

1.  In the next meeting, we will be following up and keep in touch with each other on the progress of our project

**Next Team Meeting**

The next team meeting is expected to be held **online** via **Microsoft Teams Meeting** on **June 22 2025** subject to any prevailing conditions
