---
title: "Meeting Minutes 3"
description: ""
author: "David Chiam, Enrico Sebastian, Liu Chih Yuan"
date: "22 May 2025"
date-modified: "08 June 2025"
format: html
editor: visual
execute: 
  eval: true
  echo: true
  warning: false
  freeze: true
---

**Date Conducted:** 08 June 2025

**Meeting time:** 1500hrs - 1800 hrs

**Location:** Singapore Management University

**Agenda on this meeting:**

1.  To start working on the SHINY project
2.  To discuss the answers generated by team members for the questions
3.  To analyse and discuss on the possible data that will be used for this project based on the answers provided by each of the team members for the questions

**What has been discussed during this meeting?**

1.  After a few days of self analysis on the datasets and answering the questions, we discussed on the possible datasets that can be visualised and used in our SHINY application.

2.  Once discussion is done, we will shortlist the top three visualisation methods that will be used for our project

3.  As we will also be preparing for our proposal, we also discussed on how he SHINY app will look like; be it the dashboard, menu pages, etc.

4.  Once all is laid out, we will then start to draft out the proposal to be then uploaded in our project respitory as part of our [Take Home Exercise 03](https://isss608projectgroup12.netlify.app/project_proposal/project_proposal) once everything is done

**Preparing for next Meeting:**

1.  In the next meeting, we will be finalizing our proposal for our SHINY app. This proposal will define our project aim, scope and how the SHINY app will look like

2.  Once the proposal is completed, we will also start works on our SHINY app by our next meeting

**Next Team Meeting**

The next team meeting is expected to be held **in person** at **Singapore Management University** at **1600 hrs** on **June 14 2025** subject to any prevailing conditions
