project:
  type: website

website:
  title: "ISSS608 Visual Analytics Project"
  navbar:
    left:
      - text: "Menu"
        menu:
        - text: "Project Proposal"
          href: "project_proposal/project_proposal.html"
        - text: "Report Draft (Main)"
          href: "main_project_qmd/main_project_qmd/main.html"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

