project:
  type: website

website:
  title: "ISSS608 Visual Analytics Project"
  navbar:
    left:
      - text: "Menu"
        menu:
        - text: "Project Proposal"
          href: "project_proposal/project_proposal.qmd"
        - text: "David Test"
          href: "Test_Folder/TestQuarto_David.html"
    
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

